version = 1

test_patterns = [
    "tests/**",
    "**_test.go"
]

exclude_patterns = [
    "third_party/proto/**",
    "testutil/**",
    "proto/soominhyunwoo/**",
    "contrib/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/soominhyunwoo/chain-sdk"]