[module]
description = "The bank module is responsible for handling multi-asset coin transfers between accounts and tracking special-case pseudo-transfers which must work differently with particular kinds of accounts."
homepage = "https://github.com/soominhyunwoo/chain-sdk"
keywords = [
  "tokens",
  "bank",
  "transfer",
  "asset",
  "fungible",
  "coins",
]

name = "x/bank"

[bug_tracker]
url = "https://github.com/soominhyunwoo/chain-sdk/issues"

[[authors]]
name = "alexanderbez"

[[authors]]
name = "fedekunze"

[[authors]]
name = "cwgoes"

[[authors]]
name = "alessio"

[version]
documentation = "https://raw.githubusercontent.com/soominhyunwoo/chain-sdk/master/x/bank/atlas/atlas-v0.39.1.md"
repo = "https://github.com/soominhyunwoo/chain-sdk/releases/tag/v0.39.2"
sdk_compat = "v0.39.x"
version = "v0.39.2"
