[module]
description = "The auth module is responsible for specifying the base transaction and account types for an application, as well as AnteHandler and authentication logic."
homepage = "https://github.com/soominhyunwoo/chain-sdk"
keywords = [
  "authentication",
  "signatures",
  "ante",
  "transactions",
  "accounts",
]

name = "x/auth"

[bug_tracker]
url = "https://github.com/soominhyunwoo/chain-sdk/issues"

[[authors]]
name = "alexanderbez"

[[authors]]
name = "fedekunze"

[[authors]]
name = "cwgoes"

[[authors]]
name = "alessio"

[version]
documentation = "https://raw.githubusercontent.com/soominhyunwoo/chain-sdk/master/x/auth/atlas/atlas-v0.39.1.md"
repo = "https://github.com/soominhyunwoo/chain-sdk/releases/tag/v0.39.2"
sdk_compat = "v0.39.x"
version = "v0.39.2"
